
language: python

jobs:
  include:
    - stage: Build
      os: linux
      install: &base_install
        - pip install -r requirements.txt
        - pip install pyinstaller
      script:
        - tools/download_firmware_release.sh
        - tools/build_release.sh linux
      deploy: &base_deploy
        provider: releases
        token: $GITHUB_TOKEN
        file: dist/webcontrol/*.tar.gz
        skip_cleanup: true
        draft: true
        on:
          tags: true

    - stage: Build
      os: linux
      arch: arm64
      before_install:
        - sudo apt-get -y install liblapack-dev libblas-dev gfortran
      install:
        - *base_install
      script:
        - tools/download_firmware_release.sh
        - tools/build_release.sh rpi
      deploy:
        <<: *base_deploy
